name: Constrained Programming Cookbook
description: >
  Jupyter notebooks for learning and experimenting with scheduling problems 
  using constraint programming (IBM CP Optimizer).
version: 1.0
license: MIT
repo: https://github.com/radovluk/CP_Cookbook

dependencies:
  - python=3.10
  - jupyter
  - docplex
  - matplotlib
  - numpy
  - pandas

run:
  - conda env create -f environment.yml
  - conda activate scheduling
  - jupyter notebook
